@startuml

class App{
start()
main()
}
class List{
listName
itemsList
List()
getItemsList()
setItemsList()
getListName()
setListName()
completeItems()
incompleteItems()
markComplete()
markIncomplete()
}
class Item{
-description
-dueDate
completed
getDescription()
setDescription()
getDueDate()
setDueDate()
getCompleted()
setCompleted()
}
class todoListController{
listOB
itemOB
+toDoLists
+items
addListButton()
deleteListButton()
clearListButton()
addItemButton()
deleteItemButton()
SaveDescButton()
SaveDateButton()
markCompleteButton()
markIncompleteButton()
displayCBClicked()
saveListButton()
loadListButton()
saveEdit()
saveList()
loadList()
loadSavedList()
addItem()
initialize()
}

@enduml